// Successful Responses (200-299)
export const HTTP_STATUS_OK = 200 // GET, PUT, DELETE, PATCH
export const HTTP_STATUS_CREATED = 201 // POST
export const HTTP_STATUS_ACCEPTED = 202 // POST
export const HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION = 203
export const HTTP_STATUS_NO_CONTENT = 204 // PUT, DELETE, PATCH

// Redirection Messages (300-399)
export const HTTP_STATUS_MULTIPLE_CHOICES = 300
export const HTTP_STATUS_MOVED_PERMANENTLY = 301
export const HTTP_STATUS_FOUND = 302

// Client Error Responses (400-499)
export const HTTP_STATUS_BAD_REQUEST = 400
export const HTTP_STATUS_UNAUTHORIZED = 401
export const HTTP_STATUS_PAYMENT_REQUIRED = 402
export const HTTP_STATUS_FORBIDDEN = 403
export const HTTP_STATUS_NOT_FOUND = 404
export const HTTP_STATUS_METHOD_NOT_ALLOWED = 405
export const HTTP_STATUS_NOT_ACCEPTABLE = 406
export const HTTP_STATUS_REQUEST_TIMEOUT = 408
export const HTTP_STATUS_CONFLICT = 409
export const HTTP_STATUS_PAYLOAD_TOO_LARGE = 413
export const HTTP_STATUS_URI_TOO_LONG = 414
export const HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415
export const HTTP_STATUS_EXPECTATION_FAILED = 417
export const HTTP_STATUS_UNPROCESSABLE_ENTITY = 422
export const HTTP_STATUS_LOCKED = 423
export const HTTP_STATUS_FAILED_DEPENDENCY = 424
export const HTTP_STATUS_PRECONDITION_REQUIRED = 428
export const HTTP_STATUS_TOO_MANY_REQUESTS = 429
export const HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
export const HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451

// Server Error Responses (500-599)
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
export const HTTP_STATUS_NOT_IMPLEMENTED = 501
export const HTTP_STATUS_BAD_GATEWAY = 502
export const HTTP_STATUS_SERVICE_UNAVAILABLE = 503
export const HTTP_STATUS_GATEWAY_TIMEOUT = 504
export const HTTP_STATUS_INSUFFICIENT_STORAGE = 507
export const HTTP_STATUS_LOOP_DETECTED = 508
export const HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED = 511
