import { MigrationInterface, QueryRunner } from 'typeorm'

export class WorkOrderMigration1772400000000 implements MigrationInterface {
  name = 'WorkOrderMigration1772400000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "WORK_ORDER_STATUS" ("CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "CREATED_BY" integer, "UPDATED_AT" TIMESTAMP DEFAULT now(), "UPDATED_BY" integer, "STATE" character(1) NOT NULL DEFAULT 'A', "STATUS_ID" SERIAL NOT NULL, "BUSINESS_ID" integer, "CODE" character varying(30) NOT NULL, "NAME" character varying(100) NOT NULL, "DESCRIPTION" character varying(250), "IS_FINAL" boolean NOT NULL DEFAULT false, "ORDER_INDEX" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_155a7d931f0f5736c5dd9f03d8f" PRIMARY KEY ("STATUS_ID"))`
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_WORK_ORDER_STATUS_CODE" ON "WORK_ORDER_STATUS" ("CODE")`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_WORK_ORDER_STATUS_ORDER" ON "WORK_ORDER_STATUS" ("ORDER_INDEX")`
    )
    await queryRunner.query(
      `CREATE TABLE "WORK_ORDER" ("CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "CREATED_BY" integer, "UPDATED_AT" TIMESTAMP DEFAULT now(), "UPDATED_BY" integer, "STATE" character(1) NOT NULL DEFAULT 'A', "WORK_ORDER_ID" SERIAL NOT NULL, "BUSINESS_ID" integer, "ORDER_NO" character varying(20), "CUSTOMER_ID" integer NOT NULL, "VEHICLE_ID" integer NOT NULL, "STATUS_ID" integer NOT NULL, "RECEIVED_BY_STAFF_ID" integer NOT NULL, "DELIVERED_BY_STAFF_ID" integer, "OPENED_AT" TIMESTAMP NOT NULL DEFAULT now(), "PROMISED_AT" TIMESTAMP, "CLOSED_AT" TIMESTAMP, "CANCELLED_AT" TIMESTAMP, "SYMPTOM" character varying(1000) NOT NULL, "DIAGNOSIS" text, "WORK_PERFORMED" text, "INTERNAL_NOTES" text, "CUSTOMER_OBSERVATIONS" text, "REQUIRES_DISASSEMBLY" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_83795790151453cc6aee03b76ce" PRIMARY KEY ("WORK_ORDER_ID"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_WORK_ORDER_STATUS" ON "WORK_ORDER" ("STATUS_ID")`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_WORK_ORDER_CUSTOMER" ON "WORK_ORDER" ("CUSTOMER_ID")`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_WORK_ORDER_VEHICLE" ON "WORK_ORDER" ("VEHICLE_ID")`
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_WORK_ORDER_BUSINESS_ORDER_NO" ON "WORK_ORDER" ("BUSINESS_ID", "ORDER_NO")`
    )
    await queryRunner.query(
      `CREATE TABLE "WORK_ORDER_SERVICE_LINE" ("CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "CREATED_BY" integer, "UPDATED_AT" TIMESTAMP DEFAULT now(), "UPDATED_BY" integer, "STATE" character(1) NOT NULL DEFAULT 'A', "SERVICE_LINE_ID" SERIAL NOT NULL, "WORK_ORDER_ID" integer NOT NULL, "SERVICE_TYPE" character varying(30) NOT NULL DEFAULT 'SERVICIO', "DESCRIPTION" character varying(500) NOT NULL, "QUANTITY" numeric(12,2) NOT NULL DEFAULT '1', "REFERENCE_AMOUNT" numeric(12,2) NOT NULL DEFAULT '0', "NOTES" character varying(250), CONSTRAINT "PK_8fd31dbb256c1fdc0081128480e" PRIMARY KEY ("SERVICE_LINE_ID"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_WORK_ORDER_SERVICE_LINE_WORK_ORDER" ON "WORK_ORDER_SERVICE_LINE" ("WORK_ORDER_ID")`
    )
    await queryRunner.query(
      `CREATE TABLE "WORK_ORDER_CONSUMED_ITEM" ("CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "CREATED_BY" integer, "UPDATED_AT" TIMESTAMP DEFAULT now(), "UPDATED_BY" integer, "STATE" character(1) NOT NULL DEFAULT 'A', "CONSUMED_ITEM_ID" SERIAL NOT NULL, "WORK_ORDER_ID" integer NOT NULL, "ARTICLE_ID" integer NOT NULL, "QUANTITY" numeric(12,2) NOT NULL DEFAULT '1', "UNIT_COST_REFERENCE" numeric(12,2), "NOTES" character varying(250), CONSTRAINT "PK_524fa72318d5980c4b004e80f1e" PRIMARY KEY ("CONSUMED_ITEM_ID"))`
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_WORK_ORDER_CONSUMED_ITEM_ARTICLE" ON "WORK_ORDER_CONSUMED_ITEM" ("WORK_ORDER_ID", "ARTICLE_ID")`
    )
    await queryRunner.query(
      `CREATE TABLE "WORK_ORDER_TECHNICIAN" ("CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "CREATED_BY" integer, "UPDATED_AT" TIMESTAMP DEFAULT now(), "UPDATED_BY" integer, "STATE" character(1) NOT NULL DEFAULT 'A', "WORK_ORDER_TECHNICIAN_ID" SERIAL NOT NULL, "WORK_ORDER_ID" integer NOT NULL, "STAFF_ID" integer NOT NULL, "ROLE_ON_JOB" character varying(30), "IS_LEAD" boolean NOT NULL DEFAULT false, "REFERENCE_PERCENT" numeric(5,2), "REFERENCE_AMOUNT" numeric(12,2), "NOTES" character varying(250), CONSTRAINT "PK_52f5ea0f0a97fc1adac4407a1e2" PRIMARY KEY ("WORK_ORDER_TECHNICIAN_ID"))`
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_WORK_ORDER_TECHNICIAN_STAFF" ON "WORK_ORDER_TECHNICIAN" ("WORK_ORDER_ID", "STAFF_ID")`
    )
    await queryRunner.query(
      `CREATE TABLE "WORK_ORDER_STATUS_HISTORY" ("HISTORY_ID" SERIAL NOT NULL, "WORK_ORDER_ID" integer NOT NULL, "STATUS_ID" integer NOT NULL, "CHANGED_BY_STAFF_ID" integer NOT NULL, "CHANGED_AT" TIMESTAMP NOT NULL DEFAULT now(), "NOTES" character varying(500), CONSTRAINT "PK_9d28f0f88dfb33bceab97920f4e" PRIMARY KEY ("HISTORY_ID"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_WORK_ORDER_STATUS_HISTORY_ORDER" ON "WORK_ORDER_STATUS_HISTORY" ("WORK_ORDER_ID")`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS" ADD CONSTRAINT "FK_WORK_ORDER_STATUS_BUSINESS" FOREIGN KEY ("BUSINESS_ID") REFERENCES "BUSINESS "("BUSINESS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" ADD CONSTRAINT "FK_WORK_ORDER_BUSINESS" FOREIGN KEY ("BUSINESS_ID") REFERENCES "BUSINESS "("BUSINESS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" ADD CONSTRAINT "FK_WORK_ORDER_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "PERSON"("PERSON_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" ADD CONSTRAINT "FK_WORK_ORDER_VEHICLE" FOREIGN KEY ("VEHICLE_ID") REFERENCES "VEHICLE"("VEHICLE_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" ADD CONSTRAINT "FK_WORK_ORDER_STATUS" FOREIGN KEY ("STATUS_ID") REFERENCES "WORK_ORDER_STATUS"("STATUS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" ADD CONSTRAINT "FK_WORK_ORDER_RECEIVED_BY" FOREIGN KEY ("RECEIVED_BY_STAFF_ID") REFERENCES "STAFF"("STAFF_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" ADD CONSTRAINT "FK_WORK_ORDER_DELIVERED_BY" FOREIGN KEY ("DELIVERED_BY_STAFF_ID") REFERENCES "STAFF"("STAFF_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_SERVICE_LINE" ADD CONSTRAINT "FK_WORK_ORDER_SERVICE_LINE_ORDER" FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER"("WORK_ORDER_ID") ON DELETE CASCADE ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_CONSUMED_ITEM" ADD CONSTRAINT "FK_WORK_ORDER_CONSUMED_ITEM_ORDER" FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER"("WORK_ORDER_ID") ON DELETE CASCADE ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_CONSUMED_ITEM" ADD CONSTRAINT "FK_WORK_ORDER_CONSUMED_ITEM_ARTICLE" FOREIGN KEY ("ARTICLE_ID") REFERENCES "ARTICLE"("ARTICLE_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_TECHNICIAN" ADD CONSTRAINT "FK_WORK_ORDER_TECHNICIAN_ORDER" FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER"("WORK_ORDER_ID") ON DELETE CASCADE ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_TECHNICIAN" ADD CONSTRAINT "FK_WORK_ORDER_TECHNICIAN_STAFF" FOREIGN KEY ("STAFF_ID") REFERENCES "STAFF"("STAFF_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS_HISTORY" ADD CONSTRAINT "FK_WORK_ORDER_STATUS_HISTORY_ORDER" FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER"("WORK_ORDER_ID") ON DELETE CASCADE ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS_HISTORY" ADD CONSTRAINT "FK_WORK_ORDER_STATUS_HISTORY_STATUS" FOREIGN KEY ("STATUS_ID") REFERENCES "WORK_ORDER_STATUS"("STATUS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS_HISTORY" ADD CONSTRAINT "FK_WORK_ORDER_STATUS_HISTORY_STAFF" FOREIGN KEY ("CHANGED_BY_STAFF_ID") REFERENCES "STAFF"("STAFF_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `INSERT INTO "WORK_ORDER_STATUS" ("CODE", "NAME", "DESCRIPTION", "IS_FINAL", "ORDER_INDEX", "STATE") VALUES
      ('CREADA', 'Creada', 'Orden de trabajo registrada', false, 1, 'A'),
      ('DIAGNOSTICO', 'En diagnostico', 'Revision inicial y diagnostico', false, 2, 'A'),
      ('REPARACION', 'En reparacion', 'Trabajo tecnico en proceso', false, 3, 'A'),
      ('LISTA_ENTREGA', 'Lista para entrega', 'Orden lista para entregar al cliente', false, 4, 'A'),
      ('ENTREGADA', 'Entregada/Cerrada', 'Orden cerrada y entregada', true, 5, 'A'),
      ('CANCELADA', 'Cancelada', 'Orden cancelada', true, 6, 'A')`
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM "WORK_ORDER_STATUS" WHERE "CODE" IN ('CREADA', 'DIAGNOSTICO', 'REPARACION', 'LISTA_ENTREGA', 'ENTREGADA', 'CANCELADA')`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS_HISTORY" DROP CONSTRAINT "FK_WORK_ORDER_STATUS_HISTORY_STAFF"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS_HISTORY" DROP CONSTRAINT "FK_WORK_ORDER_STATUS_HISTORY_STATUS"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS_HISTORY" DROP CONSTRAINT "FK_WORK_ORDER_STATUS_HISTORY_ORDER"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_TECHNICIAN" DROP CONSTRAINT "FK_WORK_ORDER_TECHNICIAN_STAFF"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_TECHNICIAN" DROP CONSTRAINT "FK_WORK_ORDER_TECHNICIAN_ORDER"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_CONSUMED_ITEM" DROP CONSTRAINT "FK_WORK_ORDER_CONSUMED_ITEM_ARTICLE"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_CONSUMED_ITEM" DROP CONSTRAINT "FK_WORK_ORDER_CONSUMED_ITEM_ORDER"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_SERVICE_LINE" DROP CONSTRAINT "FK_WORK_ORDER_SERVICE_LINE_ORDER"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" DROP CONSTRAINT "FK_WORK_ORDER_DELIVERED_BY"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" DROP CONSTRAINT "FK_WORK_ORDER_RECEIVED_BY"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" DROP CONSTRAINT "FK_WORK_ORDER_STATUS"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" DROP CONSTRAINT "FK_WORK_ORDER_VEHICLE"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" DROP CONSTRAINT "FK_WORK_ORDER_CUSTOMER"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER" DROP CONSTRAINT "FK_WORK_ORDER_BUSINESS"`
    )
    await queryRunner.query(
      `ALTER TABLE "WORK_ORDER_STATUS" DROP CONSTRAINT "FK_WORK_ORDER_STATUS_BUSINESS"`
    )
    await queryRunner.query(
      `DROP INDEX "public"."IDX_WORK_ORDER_STATUS_HISTORY_ORDER"`
    )
    await queryRunner.query(`DROP TABLE "WORK_ORDER_STATUS_HISTORY"`)
    await queryRunner.query(
      `DROP INDEX "public"."UQ_WORK_ORDER_TECHNICIAN_STAFF"`
    )
    await queryRunner.query(`DROP TABLE "WORK_ORDER_TECHNICIAN"`)
    await queryRunner.query(
      `DROP INDEX "public"."UQ_WORK_ORDER_CONSUMED_ITEM_ARTICLE"`
    )
    await queryRunner.query(`DROP TABLE "WORK_ORDER_CONSUMED_ITEM"`)
    await queryRunner.query(
      `DROP INDEX "public"."IDX_WORK_ORDER_SERVICE_LINE_WORK_ORDER"`
    )
    await queryRunner.query(`DROP TABLE "WORK_ORDER_SERVICE_LINE"`)
    await queryRunner.query(
      `DROP INDEX "public"."UQ_WORK_ORDER_BUSINESS_ORDER_NO"`
    )
    await queryRunner.query(`DROP INDEX "public"."IDX_WORK_ORDER_VEHICLE"`)
    await queryRunner.query(`DROP INDEX "public"."IDX_WORK_ORDER_CUSTOMER"`)
    await queryRunner.query(`DROP INDEX "public"."IDX_WORK_ORDER_STATUS"`)
    await queryRunner.query(`DROP TABLE "WORK_ORDER"`)
    await queryRunner.query(
      `DROP INDEX "public"."IDX_WORK_ORDER_STATUS_ORDER"`
    )
    await queryRunner.query(
      `DROP INDEX "public"."UQ_WORK_ORDER_STATUS_CODE"`
    )
    await queryRunner.query(`DROP TABLE "WORK_ORDER_STATUS"`)
  }
}
