import { MigrationInterface, QueryRunner } from 'typeorm'

export class InventoryMovementMigration1772500000000
  implements MigrationInterface
{
  name = 'InventoryMovementMigration1772500000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "INVENTORY_MOVEMENT" ("CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "CREATED_BY" integer, "UPDATED_AT" TIMESTAMP DEFAULT now(), "UPDATED_BY" integer, "STATE" character(1) NOT NULL DEFAULT 'A', "MOVEMENT_ID" SERIAL NOT NULL, "BUSINESS_ID" integer, "MOVEMENT_NO" character varying(20), "MOVEMENT_TYPE" character varying(30) NOT NULL, "MOVEMENT_DATE" TIMESTAMP NOT NULL DEFAULT now(), "REFERENCE_SOURCE" character varying(30) NOT NULL DEFAULT 'MANUAL', "REFERENCE_ID" integer, "NOTES" character varying(500), CONSTRAINT "PK_fd529819d0a65011e520a8bf5aa" PRIMARY KEY ("MOVEMENT_ID"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_INVENTORY_MOVEMENT_TYPE" ON "INVENTORY_MOVEMENT" ("MOVEMENT_TYPE")`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_INVENTORY_MOVEMENT_DATE" ON "INVENTORY_MOVEMENT" ("MOVEMENT_DATE")`
    )
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_INVENTORY_MOVEMENT_BUSINESS_NO" ON "INVENTORY_MOVEMENT" ("BUSINESS_ID", "MOVEMENT_NO")`
    )
    await queryRunner.query(
      `CREATE TABLE "INVENTORY_MOVEMENT_DETAIL" ("CREATED_AT" TIMESTAMP NOT NULL DEFAULT now(), "CREATED_BY" integer, "UPDATED_AT" TIMESTAMP DEFAULT now(), "UPDATED_BY" integer, "STATE" character(1) NOT NULL DEFAULT 'A', "MOVEMENT_DETAIL_ID" SERIAL NOT NULL, "MOVEMENT_ID" integer NOT NULL, "ARTICLE_ID" integer NOT NULL, "QUANTITY" numeric(12,2) NOT NULL DEFAULT '1', "UNIT_COST_REFERENCE" numeric(12,2), "NOTES" character varying(250), CONSTRAINT "PK_d8733cf95de7d06d6b3d352d965" PRIMARY KEY ("MOVEMENT_DETAIL_ID"))`
    )
    await queryRunner.query(
      `CREATE INDEX "IDX_INVENTORY_MOVEMENT_DETAIL_MOVEMENT" ON "INVENTORY_MOVEMENT_DETAIL" ("MOVEMENT_ID")`
    )
    await queryRunner.query(
      `ALTER TABLE "INVENTORY_MOVEMENT" ADD CONSTRAINT "FK_INVENTORY_MOVEMENT_BUSINESS" FOREIGN KEY ("BUSINESS_ID") REFERENCES "BUSINESS "("BUSINESS_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "INVENTORY_MOVEMENT_DETAIL" ADD CONSTRAINT "FK_INVENTORY_MOVEMENT_DETAIL_MOVEMENT" FOREIGN KEY ("MOVEMENT_ID") REFERENCES "INVENTORY_MOVEMENT"("MOVEMENT_ID") ON DELETE CASCADE ON UPDATE NO ACTION`
    )
    await queryRunner.query(
      `ALTER TABLE "INVENTORY_MOVEMENT_DETAIL" ADD CONSTRAINT "FK_INVENTORY_MOVEMENT_DETAIL_ARTICLE" FOREIGN KEY ("ARTICLE_ID") REFERENCES "ARTICLE"("ARTICLE_ID") ON DELETE NO ACTION ON UPDATE NO ACTION`
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "INVENTORY_MOVEMENT_DETAIL" DROP CONSTRAINT "FK_INVENTORY_MOVEMENT_DETAIL_ARTICLE"`
    )
    await queryRunner.query(
      `ALTER TABLE "INVENTORY_MOVEMENT_DETAIL" DROP CONSTRAINT "FK_INVENTORY_MOVEMENT_DETAIL_MOVEMENT"`
    )
    await queryRunner.query(
      `ALTER TABLE "INVENTORY_MOVEMENT" DROP CONSTRAINT "FK_INVENTORY_MOVEMENT_BUSINESS"`
    )
    await queryRunner.query(
      `DROP INDEX "public"."IDX_INVENTORY_MOVEMENT_DETAIL_MOVEMENT"`
    )
    await queryRunner.query(`DROP TABLE "INVENTORY_MOVEMENT_DETAIL"`)
    await queryRunner.query(
      `DROP INDEX "public"."UQ_INVENTORY_MOVEMENT_BUSINESS_NO"`
    )
    await queryRunner.query(`DROP INDEX "public"."IDX_INVENTORY_MOVEMENT_DATE"`)
    await queryRunner.query(`DROP INDEX "public"."IDX_INVENTORY_MOVEMENT_TYPE"`)
    await queryRunner.query(`DROP TABLE "INVENTORY_MOVEMENT"`)
  }
}
